import { z } from 'zod';
import type { Response } from 'express';
import type { AuthRequest } from '../utils/auth';
import { prisma } from '../lib/prisma';
import { fail, ok } from '../utils/response';
import { emitToUser } from '../lib/socket';

export async function startFocus(request: AuthRequest, response: Response) { const parsed = z.object({ durationMinutes: z.number().int().positive().max(480), taskId: z.string().optional() }).safeParse(request.body); if (!parsed.success) return fail(response, 'A valid focus duration is required'); const session = await prisma.focusSession.create({ data: { ...parsed.data, userId: request.userId! } }); emitToUser(request.userId!, 'focus:created', session); return ok(response, session, 201); }
export async function completeFocus(request: AuthRequest, response: Response) { const session = await prisma.focusSession.findFirst({ where: { id: String(request.params.id), userId: request.userId! } }); if (!session) return fail(response, 'Focus session not found', 404); const updated = await prisma.focusSession.update({ where: { id: session.id }, data: { status: 'COMPLETED', completedAt: new Date() } }); emitToUser(request.userId!, 'focus:completed', updated); return ok(response, updated); }
export async function focusHistory(request: AuthRequest, response: Response) { return ok(response, await prisma.focusSession.findMany({ where: { userId: request.userId }, orderBy: { startedAt: 'desc' } })); }
const journalSchema = z.object({ date: z.coerce.date(), accomplishments: z.string().max(10000).optional(), lessons: z.string().max(10000).optional(), procrastination: z.string().max(10000).optional(), improvements: z.string().max(10000).optional(), gratitude: z.string().max(10000).optional(), passionScore: z.number().int().min(1).max(10).optional() });
export async function journalList(request: AuthRequest, response: Response) { return ok(response, await prisma.journalEntry.findMany({ where: { userId: request.userId }, orderBy: { date: 'desc' } })); }
export async function journalByDate(request: AuthRequest, response: Response) { const date = new Date(`${request.params.date}T00:00:00.000Z`); return ok(response, await prisma.journalEntry.findUnique({ where: { userId_date: { userId: request.userId!, date } } })); }
export async function journalSave(request: AuthRequest, response: Response) { const parsed = journalSchema.safeParse(request.body); if (!parsed.success) return fail(response, 'Invalid journal entry'); const existing = await prisma.journalEntry.findUnique({ where: { userId_date: { userId: request.userId!, date: parsed.data.date } } }); const entry = await prisma.journalEntry.upsert({ where: { userId_date: { userId: request.userId!, date: parsed.data.date } }, update: parsed.data, create: { ...parsed.data, userId: request.userId! } }); emitToUser(request.userId!, existing ? 'journal:updated' : 'journal:created', entry); return ok(response, entry, 201); }
export async function xp(request: AuthRequest, response: Response) { const history = await prisma.xPTransaction.findMany({ where: { userId: request.userId }, orderBy: { createdAt: 'desc' } }); return ok(response, { total: history.reduce((sum, item) => sum + item.amount, 0), history }); }
export async function importBackup(request: AuthRequest, response: Response) { const input = z.object({ version: z.number(), tasks: z.array(z.object({ title: z.string().min(1).max(200), description: z.string().optional(), priority: z.enum(['LOW', 'MEDIUM', 'HIGH', 'URGENT']).optional() })).optional(), habits: z.array(z.object({ name: z.string().min(1).max(200), frequency: z.string().max(100) })).optional() }).safeParse(request.body); if (!input.success) return fail(response, 'Backup format is invalid'); const data = input.data; const result = await prisma.$transaction(async (tx) => { const tasks = data.tasks?.length ? await tx.task.createMany({ data: data.tasks.map((task) => ({ ...task, userId: request.userId! })) }) : { count: 0 }; const habits = data.habits?.length ? await tx.habit.createMany({ data: data.habits.map((habit) => ({ ...habit, userId: request.userId! })) }) : { count: 0 }; return { tasks: tasks.count, habits: habits.count }; }); return ok(response, result, 201); }