name: Deploy Frontend + Backend (Manual)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy-frontend:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit

  deploy-backend:
    uses: ./.github/workflows/deploy-backend.yml
    secrets: inherit
