name: Deploy Frontend to GitHub Pages (Manual)

on:
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
